version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.2.1
  slack: circleci/slack@3.4.2

workflows:
  lint:
    jobs:
      - lint:
          context: aws
      - build-and-deploy-charms-on-lxd:
          context: aws
          requires:
            - lint

jobs:
  lint:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: pip install tox
      - run:
          name: Run Lint
          command: |
            make lint

  build-and-deploy-charms-on-lxd:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout

      - run:
          name: "Install snapd"
          command: |
            sudo apt-get update
            sudo apt-get install --only-upgrade -y snapd
      - run:
          name: "Install charmcraft"
          command: |
            sudo snap install charmcraft --beta
      - run:
          name: "Install LXD"
          command: |
            sudo apt-get purge lxd lxd-client lxcfs
            sudo snap install lxd
            sudo lxd init --auto
            sleep 5
            sudo /snap/bin/lxd.lxc network set lxdbr0 ipv6.address none
      - run:
          name: "Install Juju"
          command: |
            sudo apt-get purge juju
            sudo snap install juju --classic
      - run:
          name: "clone charms"
          command: |
            git clone git@github.com:omnivector-solutions/slurm-charms.git
      - run:
          name: "prepare repo"
          command: |
            rm ./slurm-charms/charm-slurmdbd/requirements.txt
            echo -e "ops \ngit+https://github.com/omnivector-solutions/interface-mysql.git@master" > ./slurm-charms/charm-slurmdbd/requirements.txt
            cp -r slurm_ops_manager/* slurm-charms/charm-slurmdbd/src
            ls -la slurm-charms/charm-slurmdbd/src
            mv slurm-charms/* .
            make charms
      - run:
          name: "Install juju-wait"
          command: |
            sudo snap install juju-wait --classic
      - run:
          name: "Install jq"
          command: |
            sudo snap install jq
      - run:
          name: "Bootstrap Juju"
          command: |
            /snap/bin/juju bootstrap localhost
            /snap/bin/juju model-config logging-config="<root>=DEBUG;<unit>=DEBUG"

      - run:
          name: "Pull classic slurm snap from github"
          command: |
            make pull-classic-snap
      - run:
          name: "Deploy slurm charms using the slurm snap resource on Bionic"
          command: |
            make deploy-bionic-bundle-on-lxd-from-local-with-snap
      - run:
          name: "Wait for deployment status"
          no_output_timeout: 20m
          command: |
            export PATH=$PATH:/snap/bin
            /snap/bin/juju-wait -w -t 1150

      - run:
          name: "Show juju status"
          command: |
            /snap/bin/juju status
          when: always

      - run:
          name: Create artifacts from slurm unit logs
          command: |
            make grab-slurm-logs
            mkdir -p /tmp/slurm-unit-logs
            mv *.log /tmp/slurm-unit-logs/
          when: always

      - store_artifacts:
          path: /tmp/slurm-unit-logs
          when: always

      - save_cache:
          name: Cache built charms once we validate they successfully deploy.
          key: built-slurm-charms-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - slurmrestd.charm
            - slurmctld.charm
            - slurmdbd.charm
            - slurmd.charm
